### ISSUE TITLE
Code replacement 

### ISSUE THREAD

**Issue by gcabraldeabreu** [the-undefined/seo#5]
Move the Google analytics tracking code in the head tag

**Comment by the-undefined** [comment]
@gcabraldeabreu what is the benefit of putting it in the `<head>` tag opposed to just before the closing `</body>` tag? Just wanted to clarify as I believe the instructions dictate the latter convention. Thanks for posting!

**Comment by gcabraldeabreu** [comment]
To be honest, it's nothing but a Google standard. 
Our last SEO report pointed this out.
Google likes being the centre of SEO

**Comment by the-undefined** [comment]
Ah you are right there: 

> Paste your snippet (unaltered, in it’s entirety) into every web page you want to track. Paste it immediately before the closing </head> tag.
> ~ [source](https://support.google.com/analytics/answer/1008080?hl=en&utm_id=ad)

ha! I'm outta touch here then obviously - thanks for point that out @gcabraldeabreu :+1:
